server:
  port: ${SERVER_PORT:20232}

spring:
  datasource:
    url: ${PREPROD_DB_URL:jdbc:postgresql://preprod-db:5432/aroundu_preprod}
    username: ${PREPROD_DB_USERNAME:aroundu_preprod}
    password: ${PREPROD_DB_PASSWORD:preprodpassword}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  data:
    redis:
      port: ${PREPROD_REDIS_PORT:6379}
      host: ${PREPROD_REDIS_HOST:preprod-redis}
      password: ${PREPROD_REDIS_PASSWORD:}

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN

jwt:
  expiration:
    ms: ${PREPROD_JWT_EXPIRATION_MS:86400000}
  refresh:
    expiration:
      ms: ${PREPROD_JWT_REFRESH_EXPIRATION_MS:1209600000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: when-authorized

feature:
  enable-dummy-data: false
  enable-swagger: true
  enable-debug-security: false
