global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "aroundu-backend"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["app:8080"]
        labels:
          application: "AroundU"
          environment: "dev"

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
